In [8]:
import pandas as pd 

df = pd.read_csv('GEM_.csv')

print(df)

              Probe  Female GEM-MIX C1  Female GEM-MIX C2  Female GEM-MIX C3  \
0      A_15_P100002        1903.830553         748.509049         785.565748
1      A_15_P100003           4.466633           5.199100           5.000000
2      A_15_P100007         119.649743          86.392420          38.208540
3      A_15_P100008         123.068325         333.115297         226.191100
4      A_15_P100009          18.105415          27.767469          14.938250
...             ...                ...                ...                ...
43598  WilsonLab_58          74.289892          72.627407          42.904880
43599  WilsonLab_61          95.918078         158.076668          71.982950
43600  WilsonLab_64          27.217792         121.400447          16.950950
43601  WilsonLab_70         105.521874         215.683531         122.220000
43602   WilsonLab_9        1025.807276        2132.116758         947.238747

       Female GEM H1  Female GEM H2  Female GEM H3  Female GEM L1  \
0         930.862550     962.566102    1421.513208     979.565575
1          11.293619       5.577504       2.678306       5.000000
2          39.808562      43.048325      59.994317      58.399400
3         357.180807     421.234073     186.033832     340.596700
4          11.293619       5.577504      16.282133      11.951820
...              ...            ...            ...            ...
43598      89.086145      91.389221      35.999108     126.876200
43599     158.606367     151.808950     121.680251     127.644100
43600     203.334068     127.855690      40.465959      80.177870
43601     232.408677     181.688754     107.414738     232.791400
43602    1380.699263     916.060436     477.930143    1551.080753

       Female GEM L2  Female GEM L3
0         809.107839     871.969314
1           6.385857       3.992218
2           6.385857      15.275105
3         265.550734     211.395060
4          20.962264       8.285961
...              ...            ...
43598     144.005790      67.769844
43599      95.959448     102.647515
43600     334.282218      77.342074
43601     285.744217     194.564746
43602    2276.941110     976.899456

[43603 rows x 10 columns]

In [9]:
df.sort_values('Probe')

,Probe,Female GEM-MIX C1,Female GEM-MIX C2,Female GEM-MIX C3,Female GEM H1,Female GEM H2,Female GEM H3,Female GEM L1,Female GEM L2,Female GEM L3
0,A_15_P100002,1903.830553,748.509049,785.565748,930.862550,962.566102,1421.513208,979.565575,809.107839,871.969314
1,A_15_P100003,4.466633,5.199100,5.000000,11.293619,5.577504,2.678306,5.000000,6.385857,3.992218
2,A_15_P100007,119.649743,86.392420,38.208540,39.808562,43.048325,59.994317,58.399400,6.385857,15.275105
3,A_15_P100008,123.068325,333.115297,226.191100,357.180807,421.234073,186.033832,340.596700,265.550734,211.395060
4,A_15_P100009,18.105415,27.767469,14.938250,11.293619,5.577504,16.282133,11.951820,20.962264,8.285961
...,...,...,...,...,...,...,...,...,...,...
43598,WilsonLab_58,74.289892,72.627407,42.904880,89.086145,91.389221,35.999108,126.876200,144.005790,67.769844
43599,WilsonLab_61,95.918078,158.076668,71.982950,158.606367,151.808950,121.680251,127.644100,95.959448,102.647515
43600,WilsonLab_64,27.217792,121.400447,16.950950,203.334068,127.855690,40.465959,80.177870,334.282218,77.342074
43601,WilsonLab_70,105.521874,215.683531,122.220000,232.408677,181.688754,107.414738,232.791400,285.744217,194.564746
43602,WilsonLab_9,1025.807276,2132.116758,947.238747,1380.699263,916.060436,477.930143,1551.080753,2276.941110,976.899456

In [11]:
df.describe()

,Female GEM-MIX C1,Female GEM-MIX C2,Female GEM-MIX C3,Female GEM H1,Female GEM H2,Female GEM H3,Female GEM L1,Female GEM L2,Female GEM L3
count,43603.000000,43603.000000,43603.000000,43603.000000,43603.000000,43603.000000,43603.000000,43603.000000,43603.000000
mean,1179.359419,1214.476604,1172.165806,1206.826436,1195.051275,1149.530156,1193.242568,1191.143022,1164.674346
std,7113.928657,7226.763840,6849.144234,7053.896335,6937.544518,6709.960051,6981.904481,6887.200014,6864.903993
min,4.466633,5.199100,5.000000,11.293619,5.577504,2.678306,5.000000,6.385857,3.992218
25%,6.903614,5.199100,5.000000,11.293619,5.577504,6.661726,5.000000,6.385857,5.613295
50%,28.139214,30.846127,22.690160,24.047029,24.849364,26.165526,26.747270,30.383637,25.231546
75%,151.876051,251.010430,189.741750,241.280040,273.504175,137.332109,231.157750,237.384509,158.600050
max,176438.793900,167244.835300,137825.143700,178960.000000,166344.133700,120958.225500,151682.950600,144533.263900,153484.607100

In [20]:
>>> df_array = df.values

print(df)

              Probe  Female GEM-MIX C1  Female GEM-MIX C2  Female GEM-MIX C3  \
0      A_15_P100002        1903.830553         748.509049         785.565748
1      A_15_P100003           4.466633           5.199100           5.000000
2      A_15_P100007         119.649743          86.392420          38.208540
3      A_15_P100008         123.068325         333.115297         226.191100
4      A_15_P100009          18.105415          27.767469          14.938250
...             ...                ...                ...                ...
43598  WilsonLab_58          74.289892          72.627407          42.904880
43599  WilsonLab_61          95.918078         158.076668          71.982950
43600  WilsonLab_64          27.217792         121.400447          16.950950
43601  WilsonLab_70         105.521874         215.683531         122.220000
43602   WilsonLab_9        1025.807276        2132.116758         947.238747

       Female GEM H1  Female GEM H2  Female GEM H3  Female GEM L1  \
0         930.862550     962.566102    1421.513208     979.565575
1          11.293619       5.577504       2.678306       5.000000
2          39.808562      43.048325      59.994317      58.399400
3         357.180807     421.234073     186.033832     340.596700
4          11.293619       5.577504      16.282133      11.951820
...              ...            ...            ...            ...
43598      89.086145      91.389221      35.999108     126.876200
43599     158.606367     151.808950     121.680251     127.644100
43600     203.334068     127.855690      40.465959      80.177870
43601     232.408677     181.688754     107.414738     232.791400
43602    1380.699263     916.060436     477.930143    1551.080753

       Female GEM L2  Female GEM L3
0         809.107839     871.969314
1           6.385857       3.992218
2           6.385857      15.275105
3         265.550734     211.395060
4          20.962264       8.285961
...              ...            ...
43598     144.005790      67.769844
43599      95.959448     102.647515
43600     334.282218      77.342074
43601     285.744217     194.564746
43602    2276.941110     976.899456

[43603 rows x 10 columns]

In [21]:
df.select("Female GEM-MIX C1" "Female GEM-MIX C2")

AttributeError: 'DataFrame' object has no attribute 'select'